CREATE TABLE IF NOT EXISTS Users(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Username VARCHAR (127) NOT NULL UNIQUE,
    Name VARCHAR (127) NOT NULL,
    Email VARCHAR (127) NOT NULL UNIQUE,
    Access VARCHAR (15) NOT NULL,
    Situation VARCHAR (15) NOT NULL,
    Password VARCHAR (127) NOT NULL,
    PRIMARY KEY (ID)
)
